export interface PlatformConfig {
  name: string;
  core: string;
  extensions: string[];
  dat: string | null;
  datUrl: string | null;
  requiresBios: boolean;
  biosFiles?: string[];
}

export const PLATFORMS: Record<string, PlatformConfig> = {
  // ── Nintendo ─────────────────────────────────────────────────────────────
  NES: {
    name: 'Nintendo Entertainment System',
    core: 'nestopia',
    extensions: ['.nes', '.unf', '.unif', '.zip', '.7z'],
    dat: 'Nintendo - Nintendo Entertainment System.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Nintendo%20Entertainment%20System.dat',
    requiresBios: false,
  },
  SNES: {
    name: 'Super Nintendo Entertainment System',
    core: 'snes9x',
    extensions: ['.smc', '.sfc', '.swc', '.fig', '.bs', '.zip', '.7z'],
    dat: 'Nintendo - Super Nintendo Entertainment System.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.dat',
    requiresBios: false,
  },
  FDS: {
    name: 'Famicom Disk System',
    core: 'nestopia',
    extensions: ['.fds', '.zip', '.7z'],
    dat: 'Nintendo - Family Computer Disk System.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Family%20Computer%20Disk%20System.dat',
    requiresBios: true,
    biosFiles: ['disksys.rom'],
  },
  N64: {
    name: 'Nintendo 64',
    core: 'mupen64plus_next',
    extensions: ['.n64', '.v64', '.z64', '.bin', '.zip', '.7z'],
    dat: 'Nintendo - Nintendo 64.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Nintendo%2064.dat',
    requiresBios: false,
  },
  GB: {
    name: 'Game Boy',
    core: 'mgba',
    extensions: ['.gb', '.dmg', '.zip', '.7z'],
    dat: 'Nintendo - Game Boy.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Game%20Boy.dat',
    requiresBios: false,
  },
  GBC: {
    name: 'Game Boy Color',
    core: 'mgba',
    extensions: ['.gbc', '.zip', '.7z'],
    dat: 'Nintendo - Game Boy Color.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Game%20Boy%20Color.dat',
    requiresBios: false,
  },
  GBA: {
    name: 'Game Boy Advance',
    core: 'mgba',
    extensions: ['.gba', '.zip', '.7z'],
    dat: 'Nintendo - Game Boy Advance.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Game%20Boy%20Advance.dat',
    requiresBios: false,
  },
  NDS: {
    name: 'Nintendo DS',
    core: 'melonds',
    extensions: ['.nds', '.zip', '.7z'],
    dat: 'Nintendo - Nintendo DS.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Nintendo%20DS.dat',
    requiresBios: true,
    biosFiles: ['bios7.bin', 'bios9.bin', 'firmware.bin'],
  },
  N3DS: {
    name: 'Nintendo 3DS',
    core: 'citra',
    extensions: ['.3ds', '.3dsx', '.cci', '.cxi', '.app'],
    dat: 'Nintendo - Nintendo 3DS.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Nintendo%203DS.dat',
    requiresBios: false,
  },
  GC: {
    name: 'Nintendo GameCube',
    core: 'dolphin',
    extensions: ['.iso', '.gcm', '.gcz', '.rvz', '.wbfs'],
    dat: 'Nintendo - GameCube.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Nintendo%20-%20GameCube.dat',
    requiresBios: false,
  },
  WII: {
    name: 'Nintendo Wii',
    core: 'dolphin',
    extensions: ['.iso', '.gcz', '.rvz', '.wbfs', '.wad'],
    dat: 'Nintendo - Wii.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Nintendo%20-%20Wii.dat',
    requiresBios: false,
  },
  VIRTUALBOY: {
    name: 'Virtual Boy',
    core: 'mednafen_vb',
    extensions: ['.vb', '.vboy', '.zip', '.7z'],
    dat: 'Nintendo - Virtual Boy.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Virtual%20Boy.dat',
    requiresBios: false,
  },
  POKEMINI: {
    name: 'Pokémon Mini',
    core: 'pokemini',
    extensions: ['.min', '.zip', '.7z'],
    dat: 'Nintendo - Pokemon Mini.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Pokemon%20Mini.dat',
    requiresBios: false,
  },

  // ── Sega ─────────────────────────────────────────────────────────────────
  SG1000: {
    name: 'Sega SG-1000',
    core: 'genesis_plus_gx',
    extensions: ['.sg', '.sc', '.zip', '.7z'],
    dat: 'Sega - SG-1000.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sega%20-%20SG-1000.dat',
    requiresBios: false,
  },
  SMS: {
    name: 'Sega Master System',
    core: 'genesis_plus_gx',
    extensions: ['.sms', '.bin', '.zip', '.7z'],
    dat: 'Sega - Master System - Mark III.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sega%20-%20Master%20System%20-%20Mark%20III.dat',
    requiresBios: false,
  },
  GG: {
    name: 'Sega Game Gear',
    core: 'genesis_plus_gx',
    extensions: ['.gg', '.zip', '.7z'],
    dat: 'Sega - Game Gear.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sega%20-%20Game%20Gear.dat',
    requiresBios: false,
  },
  GEN: {
    name: 'Sega Genesis / Mega Drive',
    core: 'genesis_plus_gx',
    extensions: ['.md', '.gen', '.bin', '.smd', '.zip', '.7z'],
    dat: 'Sega - Mega Drive - Genesis.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sega%20-%20Mega%20Drive%20-%20Genesis.dat',
    requiresBios: false,
  },
  SEGACD: {
    name: 'Sega CD / Mega-CD',
    core: 'genesis_plus_gx',
    extensions: ['.chd', '.cue', '.iso', '.m3u'],
    dat: 'Sega - Mega-CD - Sega CD.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Sega%20-%20Mega%20CD%20-%20Sega%20CD.dat',
    requiresBios: true,
    biosFiles: ['bios_CD_U.bin', 'bios_CD_E.bin', 'bios_CD_J.bin'],
  },
  S32X: {
    name: 'Sega 32X',
    core: 'picodrive',
    extensions: ['.32x', '.bin', '.zip', '.7z'],
    dat: 'Sega - 32X.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sega%20-%2032X.dat',
    requiresBios: true,
    biosFiles: ['32X_G_BIOS.BIN', '32X_M_BIOS.BIN', '32X_S_BIOS.BIN'],
  },
  SATURN: {
    name: 'Sega Saturn',
    core: 'mednafen_saturn',
    extensions: ['.chd', '.cue', '.iso', '.m3u'],
    dat: 'Sega - Saturn.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Sega%20-%20Saturn.dat',
    requiresBios: true,
    biosFiles: ['sega_101.bin', 'mpr-17933.bin'],
  },
  DREAMCAST: {
    name: 'Sega Dreamcast',
    core: 'flycast',
    extensions: ['.chd', '.gdi', '.cdi', '.iso', '.m3u'],
    dat: 'Sega - Dreamcast.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Sega%20-%20Dreamcast.dat',
    requiresBios: true,
    biosFiles: ['dc_boot.bin', 'dc_flash.bin'],
  },
  SEGAPICO: {
    name: 'Sega Pico',
    core: 'genesis_plus_gx',
    extensions: ['.md', '.bin', '.zip', '.7z'],
    dat: 'Sega - PICO.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sega%20-%20PICO.dat',
    requiresBios: false,
  },

  // ── Sony ─────────────────────────────────────────────────────────────────
  PS1: {
    name: 'PlayStation',
    core: 'mednafen_psx_hw',
    extensions: ['.chd', '.cue', '.iso', '.pbp', '.m3u'],
    dat: 'Sony - PlayStation.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Sony%20-%20PlayStation.dat',
    requiresBios: true,
    biosFiles: ['scph5500.bin', 'scph5501.bin', 'scph5502.bin'],
  },
  PS2: {
    name: 'PlayStation 2',
    core: 'pcsx2',
    extensions: ['.chd', '.cso', '.iso', '.m3u'],
    dat: 'Sony - PlayStation 2.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Sony%20-%20PlayStation%202.dat',
    requiresBios: true,
    biosFiles: ['SCPH-70012.bin'],
  },
  PSP: {
    name: 'PlayStation Portable',
    core: 'ppsspp',
    extensions: ['.iso', '.cso', '.pbp', '.elf'],
    dat: 'Sony - PlayStation Portable.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sony%20-%20PlayStation%20Portable.dat',
    requiresBios: false,
  },

  // ── Atari ────────────────────────────────────────────────────────────────
  ATARI2600: {
    name: 'Atari 2600',
    core: 'stella2014',
    extensions: ['.a26', '.bin', '.zip', '.7z'],
    dat: 'Atari - 2600.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Atari%20-%202600.dat',
    requiresBios: false,
  },
  ATARI5200: {
    name: 'Atari 5200',
    core: 'a5200',
    extensions: ['.a52', '.bin', '.zip', '.7z'],
    dat: 'Atari - 5200.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Atari%20-%205200.dat',
    requiresBios: true,
    biosFiles: ['5200.rom'],
  },
  ATARI7800: {
    name: 'Atari 7800',
    core: 'prosystem',
    extensions: ['.a78', '.bin', '.zip', '.7z'],
    dat: 'Atari - 7800.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Atari%20-%207800.dat',
    requiresBios: true,
    biosFiles: ['7800 BIOS (U).rom'],
  },
  ATARI800: {
    name: 'Atari 8-bit Family',
    core: 'atari800',
    extensions: ['.xex', '.atr', '.atx', '.dcm', '.cas', '.bin', '.zip', '.7z'],
    dat: 'Atari - 8-bit Family.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Atari%20-%208-bit%20Family.dat',
    requiresBios: true,
    biosFiles: ['ATARIBAS.ROM', 'ATARIOSB.ROM', 'ATARIXL.ROM'],
  },
  ATARIJAGUAR: {
    name: 'Atari Jaguar',
    core: 'virtual_jaguar',
    extensions: ['.j64', '.jag', '.rom', '.zip', '.7z'],
    dat: 'Atari - Jaguar.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Atari%20-%20Jaguar.dat',
    requiresBios: false,
  },
  ATARILYNX: {
    name: 'Atari Lynx',
    core: 'mednafen_lynx',
    extensions: ['.lnx', '.zip', '.7z'],
    dat: 'Atari - Lynx.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Atari%20-%20Lynx.dat',
    requiresBios: true,
    biosFiles: ['lynxboot.img'],
  },
  ATARIST: {
    name: 'Atari ST',
    core: 'hatari',
    extensions: ['.st', '.stx', '.dim', '.msa', '.zip', '.7z'],
    dat: 'Atari - ST.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Atari%20-%20ST.dat',
    requiresBios: true,
    biosFiles: ['tos.img'],
  },

  // ── NEC ──────────────────────────────────────────────────────────────────
  PCENGINE: {
    name: 'PC Engine / TurboGrafx-16',
    core: 'mednafen_pce',
    extensions: ['.pce', '.zip', '.7z'],
    dat: 'NEC - PC Engine - TurboGrafx 16.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016.dat',
    requiresBios: false,
  },
  SUPERGRAFX: {
    name: 'PC Engine SuperGrafx',
    core: 'mednafen_pce',
    extensions: ['.pce', '.zip', '.7z'],
    dat: 'NEC - PC Engine SuperGrafx.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/NEC%20-%20PC%20Engine%20SuperGrafx.dat',
    requiresBios: false,
  },
  PCENGINECD: {
    name: 'PC Engine CD / TurboGrafx-CD',
    core: 'mednafen_pce',
    extensions: ['.chd', '.cue', '.iso', '.m3u'],
    dat: 'NEC - PC Engine CD - TurboGrafx-CD.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/NEC%20-%20PC%20Engine%20CD%20-%20TurboGrafx-CD.dat',
    requiresBios: true,
    biosFiles: ['syscard3.pce'],
  },
  PCFX: {
    name: 'NEC PC-FX',
    core: 'mednafen_pcfx',
    extensions: ['.chd', '.cue', '.iso', '.m3u'],
    dat: 'NEC - PC-FX.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/NEC%20-%20PC-FX.dat',
    requiresBios: true,
    biosFiles: ['pcfx.rom'],
  },
  PC88: {
    name: 'NEC PC-8801',
    core: 'quasi88',
    extensions: ['.d88', '.u88', '.m3u'],
    dat: 'NEC - PC-8001 - PC-8801.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/NEC%20-%20PC-8001%20-%20PC-8801.dat',
    requiresBios: true,
    biosFiles: ['n88.rom', 'n88n.rom'],
  },
  PC98: {
    name: 'NEC PC-9801',
    core: 'np2kai',
    extensions: ['.d98', '.hdi', '.thd', '.nhd', '.hdm', '.fdi', '.zip'],
    dat: 'NEC - PC-98.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/NEC%20-%20PC-98.dat',
    requiresBios: true,
    biosFiles: ['bios.rom', 'sound.rom', 'font.rom'],
  },

  // ── SNK ──────────────────────────────────────────────────────────────────
  NEOGEO: {
    name: 'SNK Neo Geo AES',
    core: 'fbneo',
    extensions: ['.zip', '.7z'],
    dat: 'SNK - Neo Geo.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/SNK%20-%20Neo%20Geo.dat',
    requiresBios: true,
    biosFiles: ['neogeo.zip'],
  },
  NGP: {
    name: 'Neo Geo Pocket',
    core: 'mednafen_ngp',
    extensions: ['.ngp', '.zip', '.7z'],
    dat: 'SNK - Neo Geo Pocket.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/SNK%20-%20Neo%20Geo%20Pocket.dat',
    requiresBios: false,
  },
  NGPC: {
    name: 'Neo Geo Pocket Color',
    core: 'mednafen_ngp',
    extensions: ['.ngc', '.ngp', '.zip', '.7z'],
    dat: 'SNK - Neo Geo Pocket Color.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/SNK%20-%20Neo%20Geo%20Pocket%20Color.dat',
    requiresBios: false,
  },

  // ── Commodore ────────────────────────────────────────────────────────────
  C64: {
    name: 'Commodore 64',
    core: 'vice_x64sc',
    extensions: ['.d64', '.d71', '.d81', '.t64', '.tap', '.prg', '.crt', '.zip', '.7z'],
    dat: 'Commodore - 64.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Commodore%20-%2064.dat',
    requiresBios: false,
  },
  VIC20: {
    name: 'Commodore VIC-20',
    core: 'vice_xvic',
    extensions: ['.d64', '.tap', '.prg', '.crt', '.zip', '.7z'],
    dat: 'Commodore - VIC-20.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Commodore%20-%20VIC-20.dat',
    requiresBios: false,
  },
  AMIGA: {
    name: 'Commodore Amiga',
    core: 'puae',
    extensions: ['.adf', '.adz', '.dms', '.hdf', '.hdz', '.lha', '.zip', '.7z'],
    dat: 'Commodore - Amiga.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Commodore%20-%20Amiga.dat',
    requiresBios: true,
    biosFiles: ['kick13.rom', 'kick20.rom', 'kick31.rom'],
  },
  AMIGACD32: {
    name: 'Commodore Amiga CD32',
    core: 'puae',
    extensions: ['.chd', '.cue', '.iso'],
    dat: 'Commodore - CD32.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Commodore%20-%20CD32.dat',
    requiresBios: true,
    biosFiles: ['kick40060.CD32', 'kick40060.CD32.ext'],
  },

  // ── Microsoft ────────────────────────────────────────────────────────────
  MSX: {
    name: 'MSX',
    core: 'bluemsx',
    extensions: ['.rom', '.ri', '.mx1', '.dsk', '.zip', '.7z'],
    dat: 'Microsoft - MSX.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Microsoft%20-%20MSX.dat',
    requiresBios: true,
    biosFiles: ['MSX.ROM', 'MSXDOS.ROM'],
  },
  MSX2: {
    name: 'MSX2',
    core: 'bluemsx',
    extensions: ['.rom', '.ri', '.mx2', '.dsk', '.zip', '.7z'],
    dat: 'Microsoft - MSX2.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Microsoft%20-%20MSX2.dat',
    requiresBios: true,
    biosFiles: ['MSX2.ROM', 'MSX2EXT.ROM', 'DISK.ROM'],
  },

  // ── Bandai ───────────────────────────────────────────────────────────────
  WONDERSWAN: {
    name: 'WonderSwan',
    core: 'mednafen_wswan',
    extensions: ['.ws', '.zip', '.7z'],
    dat: 'Bandai - WonderSwan.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Bandai%20-%20WonderSwan.dat',
    requiresBios: false,
  },
  WONDERSWANCOLOR: {
    name: 'WonderSwan Color',
    core: 'mednafen_wswan',
    extensions: ['.wsc', '.ws', '.zip', '.7z'],
    dat: 'Bandai - WonderSwan Color.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Bandai%20-%20WonderSwan%20Color.dat',
    requiresBios: false,
  },

  // ── Philips ──────────────────────────────────────────────────────────────
  CDI: {
    name: 'Philips CD-i',
    core: 'same_cdi',
    extensions: ['.chd', '.cue', '.iso'],
    dat: 'Philips - CD-i.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Philips%20-%20CD-i.dat',
    requiresBios: true,
    biosFiles: ['cdibios.zip'],
  },

  // ── Others ───────────────────────────────────────────────────────────────
  COLECO: {
    name: 'ColecoVision',
    core: 'gearcoleco',
    extensions: ['.col', '.rom', '.bin', '.zip', '.7z'],
    dat: 'Coleco - ColecoVision.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Coleco%20-%20ColecoVision.dat',
    requiresBios: true,
    biosFiles: ['coleco.rom'],
  },
  INTELLIVISION: {
    name: 'Mattel Intellivision',
    core: 'freeintv',
    extensions: ['.int', '.bin', '.rom', '.zip', '.7z'],
    dat: 'Mattel - Intellivision.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Mattel%20-%20Intellivision.dat',
    requiresBios: true,
    biosFiles: ['exec.bin', 'grom.bin'],
  },
  VECTREX: {
    name: 'GCE Vectrex',
    core: 'vecx',
    extensions: ['.vec', '.bin', '.zip', '.7z'],
    dat: 'GCE - Vectrex.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/GCE%20-%20Vectrex.dat',
    requiresBios: false,
  },
  ODYSSEY2: {
    name: 'Magnavox Odyssey 2',
    core: 'o2em',
    extensions: ['.bin', '.zip', '.7z'],
    dat: 'Magnavox - Odyssey2.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Magnavox%20-%20Odyssey2.dat',
    requiresBios: true,
    biosFiles: ['o2rom.bin'],
  },
  CHANNELF: {
    name: 'Fairchild Channel F',
    core: 'freechaf',
    extensions: ['.bin', '.chf', '.zip', '.7z'],
    dat: 'Fairchild - Channel F.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Fairchild%20-%20Channel%20F.dat',
    requiresBios: true,
    biosFiles: ['sl31253.bin', 'sl31254.bin'],
  },
  AMSTRADCPC: {
    name: 'Amstrad CPC',
    core: 'cap32',
    extensions: ['.dsk', '.sna', '.zip', '.7z'],
    dat: 'Amstrad - CPC.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Amstrad%20-%20CPC.dat',
    requiresBios: false,
  },
  X68000: {
    name: 'Sharp X68000',
    core: 'px68k',
    extensions: ['.dim', '.img', '.d88', '.88d', '.hdm', '.xdf', '.hdf', '.cmd', '.zip', '.7z'],
    dat: 'Sharp - X68000.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sharp%20-%20X68000.dat',
    requiresBios: true,
    biosFiles: ['iplrom.dat', 'cgrom.dat'],
  },
  APPLEII: {
    name: 'Apple II',
    core: 'mame',
    extensions: ['.dsk', '.do', '.po', '.nib', '.woz', '.zip', '.7z'],
    dat: 'Apple - II.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Apple%20-%20II.dat',
    requiresBios: false,
  },

  // ── Arcade ───────────────────────────────────────────────────────────────
  MAME: {
    name: 'MAME',
    core: 'mame2003_plus',
    extensions: ['.zip', '.7z'],
    // MAME 2003-Plus dat lives in the core repo, not libretro-database
    dat: null,
    datUrl: null,
    requiresBios: false,
  },
  FBNEO: {
    name: 'FinalBurn Neo',
    core: 'fbneo',
    extensions: ['.zip', '.7z'],
    dat: 'FBNeo - Arcade Games.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/fbneo-split/FBNeo%20-%20Arcade%20Games.dat',
    requiresBios: false,
  },

  // ── DOS / PC ─────────────────────────────────────────────────────────────
  DOS: {
    name: 'DOS',
    core: 'dosbox_pure',
    extensions: ['.exe', '.com', '.bat', '.conf', '.zip', '.7z'],
    dat: 'DOS.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/dat/DOS.dat',
    requiresBios: false,
  },

  // ── Other / Engine-based ─────────────────────────────────────────────────
  SCUMMVM: {
    name: 'ScummVM',
    core: 'scummvm',
    extensions: ['.scummvm'],
    dat: 'ScummVM.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/dat/ScummVM.dat',
    requiresBios: false,
  },
  PICO8: {
    name: 'PICO-8',
    core: 'retro8',
    extensions: ['.p8', '.p8.png'],
    dat: 'PICO-8.dat',
    datUrl: null,
    requiresBios: false,
  },

  // ── 3DO ─────────────────────────────────────────────────────────────────
  '3DO': {
    name: '3DO Interactive Multiplayer',
    core: 'opera',
    extensions: ['.chd', '.cue', '.iso'],
    dat: 'The 3DO Company - 3DO.dat',
    datUrl: 'https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/The%203DO%20Company%20-%203DO.dat',
    requiresBios: true,
    biosFiles: ['panafz10.bin'],
  },
};
